<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Brows.Composition" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Brows.Win32.Interop.Operations\Brows.Win32.Interop.Operations.csproj" />
  </ItemGroup>
</Project>
